# Use official node image as the base image
FROM node:20-alpine as build

RUN npm install -g @angular/cli@13

# Set the working directory
WORKDIR /app

COPY package*.json .
RUN npm ci
COPY . .
RUN npm run build

# Stage 2: Serve app with nginx server

# Use official nginx image as the base image
FROM nginx:alpine

WORKDIR /usr/share/nginx/html
# Copy the build output to replace the default nginx contents.
COPY --from=build /app/dist/front-end/browser .

# Expose port 80
EXPOSE 80